#!/bin/bash

if [ $# -eq 2 ]; then
        host=$1
        hex=$2
else
        echo "usage: $0 <host> <hex file>"
        exit 1
fi

if [ ! -e $hex ]
then
        echo "unable to find hex file $hex"
        exit 1
fi

/usr/bin/expect << EOF
set timeout 20

spawn telnet $host

expect "'^]'."
send "+++AT GPIO2 2 100\r"
expect "RESET"
EOF

programmer=stk500
programmer=avrisp
echo avrdude -v -v -c $programmer -p m328p -P net:$host:23 -F -U flash:w:$hex:i
avrdude -v -v -c $programmer -p m328p -P net:$host:23 -F -U flash:w:$hex:i
